addSbtPlugin("com.jsuereth"       % "sbt-pgp"      % "1.1.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"  % "1.0.7")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "2.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs" % "0.6.22")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"         % "0.3.1")  // (1)
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.3.1")  // (2)
